name: CI
on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: actions/setup-node@v2
      with:
       node-version: '12'
    - run: |
            npm install -g appium@v1.20.2
            appium -v
            appium &>/dev/null &
    - name: Checkout
      uses: actions/checkout@v2
    - name: Katalon Studio Github Action
      uses: katalon-studio/katalon-studio-github-action@v3.0
      with:
          version: '9.2.0'
          projectPath: '${{ github.workspace }}'
          args: '--config -webui.autoUpdateDrivers=true -noSplash -retry=0 -browserType=Chrome -statusDelay=15 -testSuitePath="Test Suites/TS_RegressionTest" -apiKey=${{ secrets.KATALON_API_KEY }}-browserType="Android" -deviceId="emulator-5554" -executionProfile="default" -apiKey="4fc909b3-6365-4efa-a8d0-2522727214ad" --config -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY -proxy.system.applyToDesiredCapabilities=true'
    - name: Upload Reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Katalon Reports
        path: ${{ github.workspace }}/Reports/**/*
  
