name: Simulater
on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        
      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
      - name: run tests
        uses: NguyenDuyThanhB1909984/android-emulator-runner@v2.30.1
        with:
          api-level: 29
          script: |
            echo $GITHUB_REPOSITORY
            adb devices
            
      - name: Enable emulator
      
        run: |
          /usr/bin/sh -c \/usr/local/lib/android/sdk/emulator/emulator -avd test -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim &

  

           
