name: CI
on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install specific version of Chrome
      run: |
        $ChromeVersion = "120.0.6099.217"
        Invoke-WebRequest "https://dl.google.com/tag/s/dl/chrome/install/$ChromeVersion/chrome_installer.exe" -OutFile "chrome_installer.exe"
        Start-Process chrome_installer.exe -ArgumentList '/silent', '/install' -Wait
  
    - name: Install specific ChromeDriver
      run: |
        $ChromeMajorVersion = "120.0.6099.217"
        $ChromeDriverVersion = Invoke-RestMethod -Uri "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$ChromeMajorVersion"
        Invoke-WebRequest "https://chromedriver.storage.googleapis.com/$ChromeDriverVersion/chromedriver_win32.zip" -OutFile "chromedriver_win32.zip"
        Expand-Archive "chromedriver_win32.zip" -DestinationPath "C:\Windows\System32"

    - name: Katalon Studio Github Action
      uses: katalon-studio/katalon-studio-github-action@v3.0
      with:
          version: '8.5.5'
          projectPath: '${{ github.workspace }}'
          args: '-noSplash -retry=0 -browserType=Chrome -statusDelay=15 -testSuitePath="Test Suites/TS_RegressionTest" -apiKey=${{ secrets.KATALON_API_KEY }} --config -webui.autoUpdateDrivers=true'

    - name: Upload Reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Katalon Reports
        path: ${{ github.workspace }}/Reports/**/*
