name: CI
on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Katalon Studio Github Action
      uses: katalon-studio/katalon-studio-github-action@v3.0
      with:
          version: '8.5.5'
          projectPath: '${{ github.workspace }}'
          args: '-noSplash -retry=0 -browserType=Chrome -statusDelay=15 -testSuitePath="Test Suites/TS_RegressionTest" -apiKey=${{ secrets.KATALON_API_KEY }} --config -webui.autoUpdateDrivers=true -webDriverConfigPath: "%ProgramFiles%\Katalon_Studio_Windows_{version}\configuration\resources\drivers\chromedriver.exe"'
    - name: Download ChromeDriver
      run: |
            curl -L https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/120.0.6099.109/win32/chromedriver-win32.zip -o chromedriver.zip
    - name: Unzip ChromeDriver
      run: |
          unzip chromedriver.zip
    - name: Copy Chrome driver to Katalon Studio directory
      run: |
          # Define target location based on your extracted Katalon Studio folder
          cp chromedriver.exe "path/to/katalon_studio/configuration/resources/drivers"
    - name: Upload Reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Katalon Reports
        path: ${{ github.workspace }}/Reports/**/*
