name: CI
on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: nanasess/setup-chromedriver@v2
      with:
        # Optional: do not specify to match Chrome's version
        chromedriver-version: '120.0.6099.217'
    - run: chromedriver --url-base=/wd/hub &

    - name: Katalon Studio Github Action
      uses: katalon-studio/katalon-studio-github-action@v3.0
      with:
          version: '8.5.5'
          projectPath: '${{ github.workspace }}'
          args: '-noSplash -retry=0 -browserType=Chrome -statusDelay=15 -testSuitePath="Test Suites/TS_RegressionTest" -apiKey=${{ secrets.KATALON_API_KEY }}'

    - name: Upload Reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Katalon Reports
        path: ${{ github.workspace }}/Reports/**/*
