name: CI
on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Download ChromeDriver
      run: |
          curl -L https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/120.0.6099.109/win32/chromedriver-win32.zip -o chromedriver.zip
    - name: Download and Unzip ChromeDriver
      run: |
          unzip chromedriver.zip
    - name: Katalon Studio Github Action
      uses: katalon-studio/katalon-studio-github-action@v3.0
      with:
          version: '8.5.5'
          projectPath: '${{ github.workspace }}'
          args: '-noSplash -retry=0 -browserType=Chrome -statusDelay=15 -testSuitePath="Test Suites/TS_RegressionTest" -apiKey=${{ secrets.KATALON_API_KEY }} -Dwebdriver.chrome.driver=chromedriver-win32/chromedriver.exe'
    - name: Upload Reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Katalon Reports
        path: ${{ github.workspace }}/Reports/**/*
